In [57]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [58]:
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [59]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
print("Logistic Regression: ", lr.score(X_test, y_test))

Logistic Regression:  0.9583333333333334


c:\Users\shekh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [60]:
svm = SVC()
svm.fit(X_train, y_train)
print("SVM: ", svm.score(X_test, y_test))

SVM:  0.9888888888888889


In [61]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
print("Random Forest: ", rf.score(X_test, y_test))


Random Forest:  0.9805555555555555


In [62]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [64]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [65]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [66]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9888888888888889

In [67]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [70]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    print(train_index, test_index)
    break
    # X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    # scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    # scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    # scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

[599 600 601 602 603 604 605 606 607 608] [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9] [599 600 601 602 603 604 605 606 607 608]
[0 1 2 3 4 5 6 7 8 9] [1198 1199 1200 1201 1202 1203 1204 1205 1206 1207]
