In [118]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [119]:
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [120]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
print("Logistic Regression: ", lr.score(X_test, y_test))

Logistic Regression:  0.975


c:\Users\shekh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [121]:
svm = SVC()
svm.fit(X_train, y_train)
print("SVM: ", svm.score(X_test, y_test))

SVM:  0.9888888888888889


In [122]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
print("Random Forest: ", rf.score(X_test, y_test))


Random Forest:  0.9833333333333333


In [123]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [124]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [125]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [126]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.9888888888888889

In [127]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [128]:
digits.data.size

115008

In [129]:
# raw implementation of cross validation
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))

c:\Users\shekh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\shekh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [130]:
print("Logistic Regression: ", scores_logistic)
print("SVM: ", np.mean(scores_svm))
print("Random Forest: ", np.mean(scores_rf))

Logistic Regression:  [0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
SVM:  0.9677239844184752
Random Forest:  0.9360044518642181


In [132]:
from sklearn.model_selection import cross_val_score

print("Logistic Regression: ", cross_val_score(LogisticRegression(), digits.data, digits.target))
print("SVM: ", cross_val_score(SVC(), digits.data, digits.target))
print("Random Forest: ", cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target))

c:\Users\shekh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\shekh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

Logistic Regression:  [0.92222222 0.86944444 0.94150418 0.93871866 0.89693593]
SVM:  [0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
Random Forest:  [0.91666667 0.89166667 0.95821727 0.95821727 0.91364903]
